const authActionTypes = {
	AUTH_LOGIN_IS_LOADING: 'AUTH_LOGIN_IS_LOADING',
	AUTH_LOGIN_SUCCESSFUL: 'AUTH_LOGIN_SUCCESSFUL',
	AUTH_LOGOUT: 'AUTH_LOGOUT',
	AUTH_REGISTER_IS_LOADING: 'AUTH_REGISTER_IS_LOADING',
	AUTH_REGISTER_SUCCESSFUL: 'AUTH_REGISTER_SUCCESSFUL',
	AUTH_IS_DELETING: 'AUTH_IS_DELETING',
	AUTH_DELETED_SUCCESSFUL: 'AUTH_DELETED_SUCCESSFUL',
	SET_TOKEN: 'SET_TOKEN',
	SET_REMEMBER: 'SET_REMEMBER',
}

export default authActionTypes;